// `.env.json` is generated by the `npm run build` command
// import * as env from './.env.json';

export const environment = {
    production: true,
    version: '1.0',
    serverUrl: 'https://api.chucknorris.io'
};
